insert into restaurant(name, address) values("Tokyo", "123 Truong Son, Tan Binh District, HCM City")
insert into restaurant(name, address) values("Hanuri", "15 Cong Hoa, Tan Binh District, HCM City")
insert into restaurant(name, address) values("KFC Cong Hoa", "156 Cong Hoa, Tan Binh District, HCM City")
insert into restaurant(name, address) values("KFC 456", "456 Phuoc Long B, District 9, HCM City")
insert into restaurant(name, address) values("KFC Vo Van Ngan", "156 Vo Van Ngan, Thu Duc City")

insert into menu(name, restaurant_id) values("Breakfast", 1)
insert into menu(name, restaurant_id) values("Noon", 1)
insert into menu(name, restaurant_id) values("Dinner", 1)
insert into menu(name, restaurant_id) values("Starters", 2)
insert into menu(name, restaurant_id) values("Snacks", 2)
insert into menu(name, restaurant_id) values("Desserts", 2)
insert into menu(name, restaurant_id) values("Main Courses", 2)
insert into menu(name, restaurant_id) values("Drinks", 2)
insert into menu(name, restaurant_id) values("Chips", 3)
insert into menu(name, restaurant_id) values("Drinks", 3)
insert into menu(name, restaurant_id) values("Fried Chickens", 3)
